spring.application.name=DeliveryService

server.port=8080

# spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_products
#spring.datasource.url=jdbc:postgresql://dpg-cp69oo63e1ms73a7gia0-a.frankfurt-postgres.render.com/delivery_products
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=delivery_products_user
#spring.datasource.password=4BZtDp8ZlE4hJi8MvcUVRdkfd2V3LxM8

spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_products
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret.access = "sekretkey123accesssekretkey123accesssekretkey123access"